name: Publish package to GitHub Packages

on:
  push:
    branches: ['release']

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./datase
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run tests
        run: ./gradlew test
      - name: Publish package
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: publish
          build-root-directory: ./datase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
